"""relational kitchen schema"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015_relational_kitchen"
down_revision: str | None = "0014_kitchen_generation_jobs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", name="uq_equipment_name"),
    )
    op.create_index(op.f("ix_equipment_household_id"), "equipment", ["household_id"], unique=False)
    op.create_table(
        "food_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=True),
        sa.Column("default_portion_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", name="uq_food_item_name"),
    )
    op.create_index(
        op.f("ix_food_items_household_id"), "food_items", ["household_id"], unique=False
    )
    op.create_table(
        "guidance_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guidance_rules_household_id"), "guidance_rules", ["household_id"], unique=False
    )
    op.create_table(
        "kitchen_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "name", name="uq_kitchen_tag_name"),
    )
    op.create_index(
        op.f("ix_kitchen_tags_household_id"), "kitchen_tags", ["household_id"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_household_id"),
        "knowledge_documents",
        ["household_id"],
        unique=False,
    )
    op.create_table(
        "meal_style_presets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("emoji", sa.String(length=16), nullable=True),
        sa.Column("tint", sa.String(length=16), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "key", name="uq_meal_style_preset_key"),
    )
    op.create_index(
        op.f("ix_meal_style_presets_household_id"),
        "meal_style_presets",
        ["household_id"],
        unique=False,
    )
    op.create_table(
        "weekly_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("base_plan_id", sa.Uuid(), nullable=True),
        sa.Column("base_version", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("version >= 1", name="ck_weekly_plan_version"),
        sa.ForeignKeyConstraint(["base_plan_id"], ["weekly_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weekly_plan_household_week",
        "weekly_plans",
        ["household_id", "week_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_plans_household_id"), "weekly_plans", ["household_id"], unique=False
    )
    op.create_table(
        "weekly_prompts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "week_start", name="uq_weekly_prompt_week"),
    )
    op.create_index(
        op.f("ix_weekly_prompts_household_id"), "weekly_prompts", ["household_id"], unique=False
    )
    op.create_table(
        "guidance_rule_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["guidance_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "version", name="uq_guidance_version"),
    )
    op.create_index(
        op.f("ix_guidance_rule_versions_rule_id"),
        "guidance_rule_versions",
        ["rule_id"],
        unique=False,
    )
    op.create_table(
        "kitchen_audit_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.String(length=200), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("entity_id", sa.String(length=200), nullable=True),
        sa.Column("undo", sa.JSON(), nullable=True),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kitchen_audit_entries_household_id"),
        "kitchen_audit_entries",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        "ix_kitchen_audit_household_time",
        "kitchen_audit_entries",
        ["household_id", "at"],
        unique=False,
    )
    op.create_table(
        "kitchen_recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("cuisine", sa.String(length=60), nullable=True),
        sa.Column("hero_media_id", sa.Uuid(), nullable=True),
        sa.Column("servings", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("active_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("elapsed_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("incomplete", sa.Boolean(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("elapsed_minutes >= active_minutes", name="ck_recipe_elapsed_ge_active"),
        sa.CheckConstraint("servings > 0", name="ck_recipe_servings_positive"),
        sa.ForeignKeyConstraint(["hero_media_id"], ["media_objects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kitchen_recipes_household_id"), "kitchen_recipes", ["household_id"], unique=False
    )
    op.create_table(
        "knowledge_document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version", name="uq_knowledge_version"),
    )
    op.create_index(
        op.f("ix_knowledge_document_versions_document_id"),
        "knowledge_document_versions",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "meals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("active_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("elapsed_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "day", "slot", name="uq_meal_plan_day_slot"),
    )
    op.create_index(op.f("ix_meals_plan_id"), "meals", ["plan_id"], unique=False)
    op.create_table(
        "plan_chat_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_chat_messages_plan_id"), "plan_chat_messages", ["plan_id"], unique=False
    )
    op.create_table(
        "plan_presets",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("preset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["preset_id"], ["meal_style_presets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_id", "preset_id"),
    )
    op.create_table(
        "inventory_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("food_item_id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=True),
        sa.Column("portion_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("location", sa.String(length=16), nullable=False),
        sa.Column("prepared", sa.Boolean(), nullable=False),
        sa.Column("stored_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("priority", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_batches_food_item_id"),
        "inventory_batches",
        ["food_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_batches_household_id"),
        "inventory_batches",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_batches_recipe_id"), "inventory_batches", ["recipe_id"], unique=False
    )
    op.create_table(
        "kitchen_recipe_ratings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("stars BETWEEN 1 AND 5", name="ck_kitchen_rating_stars"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "account_id", name="uq_kitchen_rating_account"),
    )
    op.create_index(
        op.f("ix_kitchen_recipe_ratings_recipe_id"),
        "kitchen_recipe_ratings",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "kitchen_recipe_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("title_en", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("active_minutes", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("wait_minutes", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "position", name="uq_recipe_step_position"),
    )
    op.create_index(
        op.f("ix_kitchen_recipe_steps_recipe_id"),
        "kitchen_recipe_steps",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "kitchen_recipe_tags",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["kitchen_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id", "tag_id"),
    )
    op.create_table(
        "meal_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("audit_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["audit_id"], ["kitchen_audit_entries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meal_events_meal_id"), "meal_events", ["meal_id"], unique=False)
    op.create_table(
        "meal_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meal_id", "position", name="uq_meal_step_position"),
    )
    op.create_index(op.f("ix_meal_steps_meal_id"), "meal_steps", ["meal_id"], unique=False)
    op.create_table(
        "plan_chat_references",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["plan_chat_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "meal_id"),
    )
    op.create_table(
        "plan_guidance_snapshots",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("guidance_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guidance_version_id"], ["guidance_rule_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_id", "guidance_version_id"),
    )
    op.create_table(
        "plan_knowledge_snapshots",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["knowledge_document_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_id", "document_version_id"),
    )
    op.create_table(
        "recipe_equipment",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id", "equipment_id"),
    )
    op.create_table(
        "recipe_ingredient_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("food_item_id", sa.Uuid(), nullable=False),
        sa.Column("group_label", sa.String(length=60), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "position", name="uq_kitchen_recipe_ingredient_position"),
    )
    op.create_index(
        op.f("ix_recipe_ingredient_items_food_item_id"),
        "recipe_ingredient_items",
        ["food_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_ingredient_items_recipe_id"),
        "recipe_ingredient_items",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "recipe_meal_slots",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id", "slot"),
    )
    op.create_table(
        "recipe_nutrition",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("calories", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("protein_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("carbs_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fat_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fiber_g", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id"),
    )
    op.create_table(
        "recipe_reheat_instructions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_reheat_instructions_recipe_id"),
        "recipe_reheat_instructions",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "prep_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("planned_portions", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("actual_portions", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("active_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("elapsed_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column("output_batch_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["output_batch_id"], ["inventory_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["weekly_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prep_tasks_plan_id"), "prep_tasks", ["plan_id"], unique=False)
    op.create_table(
        "inventory_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=True),
        sa.Column("prep_task_id", sa.Uuid(), nullable=True),
        sa.Column("audit_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["kitchen_audit_entries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["batch_id"], ["inventory_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_ledger_batch_time",
        "inventory_ledger_entries",
        ["batch_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_ledger_entries_household_id"),
        "inventory_ledger_entries",
        ["household_id"],
        unique=False,
    )
    op.create_table(
        "meal_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("portions", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("food_item_id", sa.Uuid(), nullable=True),
        sa.Column("recipe_id", sa.Uuid(), nullable=True),
        sa.Column("inventory_batch_id", sa.Uuid(), nullable=True),
        sa.Column("prep_task_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "food_item_id IS NOT NULL OR recipe_id IS NOT NULL "
            "OR inventory_batch_id IS NOT NULL OR prep_task_id IS NOT NULL",
            name="ck_meal_component_reference",
        ),
        sa.CheckConstraint("portions > 0", name="ck_meal_component_portions"),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["inventory_batch_id"], ["inventory_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meal_components_meal_id"), "meal_components", ["meal_id"], unique=False
    )
    op.create_table(
        "prep_task_dependencies",
        sa.Column("prep_task_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_prep_task_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "prep_task_id <> depends_on_prep_task_id", name="ck_prep_dependency_not_self"
        ),
        sa.ForeignKeyConstraint(["depends_on_prep_task_id"], ["prep_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("prep_task_id", "depends_on_prep_task_id"),
    )
    op.create_table(
        "prep_task_equipment",
        sa.Column("prep_task_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("prep_task_id", "equipment_id"),
    )
    op.create_table(
        "prep_task_inputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prep_task_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_batch_id", sa.Uuid(), nullable=False),
        sa.Column("portions", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_batch_id"], ["inventory_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prep_task_inputs_prep_task_id"), "prep_task_inputs", ["prep_task_id"], unique=False
    )
    op.create_table(
        "prep_task_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prep_task_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["prep_task_id"], ["prep_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prep_task_id", "position", name="uq_prep_step_position"),
    )
    op.create_index(
        op.f("ix_prep_task_steps_prep_task_id"), "prep_task_steps", ["prep_task_id"], unique=False
    )


def downgrade() -> None:
    op.drop_table("prep_task_steps")
    op.drop_table("prep_task_inputs")
    op.drop_table("prep_task_equipment")
    op.drop_table("prep_task_dependencies")
    op.drop_table("meal_components")
    op.drop_table("inventory_ledger_entries")
    op.drop_table("prep_tasks")
    op.drop_table("recipe_reheat_instructions")
    op.drop_table("recipe_nutrition")
    op.drop_table("recipe_meal_slots")
    op.drop_table("recipe_ingredient_items")
    op.drop_table("recipe_equipment")
    op.drop_table("plan_knowledge_snapshots")
    op.drop_table("plan_guidance_snapshots")
    op.drop_table("plan_chat_references")
    op.drop_table("meal_steps")
    op.drop_table("meal_events")
    op.drop_table("kitchen_recipe_tags")
    op.drop_table("kitchen_recipe_steps")
    op.drop_table("kitchen_recipe_ratings")
    op.drop_table("inventory_batches")
    op.drop_table("plan_presets")
    op.drop_table("plan_chat_messages")
    op.drop_table("meals")
    op.drop_table("knowledge_document_versions")
    op.drop_table("kitchen_recipes")
    op.drop_table("kitchen_audit_entries")
    op.drop_table("guidance_rule_versions")
    op.drop_table("weekly_prompts")
    op.drop_table("weekly_plans")
    op.drop_table("meal_style_presets")
    op.drop_table("knowledge_documents")
    op.drop_table("kitchen_tags")
    op.drop_table("guidance_rules")
    op.drop_table("food_items")
    op.drop_table("equipment")
