"""legacy ids, recipe category, allergens, kitchen settings"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0016_kitchen_backfill_fields"
down_revision: str | None = "0015_relational_kitchen"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "household_kitchen_settings",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("people", sa.Integer(), nullable=False),
        sa.Column("child_age_months", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("generate_time", sa.String(length=5), nullable=False),
        sa.Column("prep_day", sa.Integer(), nullable=False),
        sa.Column("max_prep_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_daily_active_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("new_recipes_per_week", sa.Integer(), nullable=False),
        sa.Column("recipe_repeat_gap_days", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("household_id"),
    )
    op.create_table(
        "household_allergies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("food_item_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["food_item_id"], ["food_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "label", name="uq_household_allergy"),
    )
    op.create_index(
        op.f("ix_household_allergies_household_id"),
        "household_allergies",
        ["household_id"],
        unique=False,
    )
    op.create_table(
        "recipe_allergens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["kitchen_recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_id", "label", name="uq_recipe_allergen"),
    )
    op.create_index(
        op.f("ix_recipe_allergens_recipe_id"), "recipe_allergens", ["recipe_id"], unique=False
    )
    op.add_column("guidance_rules", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint(
        "uq_guidance_rule_legacy", "guidance_rules", ["household_id", "legacy_id"]
    )
    op.add_column("inventory_batches", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint(
        "uq_inventory_batch_legacy", "inventory_batches", ["household_id", "legacy_id"]
    )
    op.add_column(
        "kitchen_audit_entries", sa.Column("legacy_id", sa.String(length=200), nullable=True)
    )
    op.create_unique_constraint(
        "uq_kitchen_audit_legacy", "kitchen_audit_entries", ["household_id", "legacy_id"]
    )
    op.add_column("kitchen_recipes", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.add_column("kitchen_recipes", sa.Column("category", sa.String(length=16), nullable=False))
    op.create_unique_constraint(
        "uq_kitchen_recipe_legacy", "kitchen_recipes", ["household_id", "legacy_id"]
    )
    op.add_column(
        "knowledge_documents", sa.Column("legacy_id", sa.String(length=200), nullable=True)
    )
    op.create_unique_constraint(
        "uq_knowledge_document_legacy", "knowledge_documents", ["household_id", "legacy_id"]
    )
    op.add_column("meal_components", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint(
        "uq_meal_component_legacy", "meal_components", ["meal_id", "legacy_id"]
    )
    op.add_column("meals", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint("uq_meal_legacy", "meals", ["plan_id", "legacy_id"])
    op.add_column("prep_tasks", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint("uq_prep_task_legacy", "prep_tasks", ["plan_id", "legacy_id"])
    op.add_column("weekly_plans", sa.Column("legacy_id", sa.String(length=200), nullable=True))
    op.create_unique_constraint(
        "uq_weekly_plan_legacy", "weekly_plans", ["household_id", "legacy_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_weekly_plan_legacy", "weekly_plans", type_="unique")
    op.drop_column("weekly_plans", "legacy_id")
    op.drop_constraint("uq_prep_task_legacy", "prep_tasks", type_="unique")
    op.drop_column("prep_tasks", "legacy_id")
    op.drop_constraint("uq_meal_legacy", "meals", type_="unique")
    op.drop_column("meals", "legacy_id")
    op.drop_constraint("uq_meal_component_legacy", "meal_components", type_="unique")
    op.drop_column("meal_components", "legacy_id")
    op.drop_constraint("uq_knowledge_document_legacy", "knowledge_documents", type_="unique")
    op.drop_column("knowledge_documents", "legacy_id")
    op.drop_constraint("uq_kitchen_recipe_legacy", "kitchen_recipes", type_="unique")
    op.drop_column("kitchen_recipes", "category")
    op.drop_column("kitchen_recipes", "legacy_id")
    op.drop_constraint("uq_kitchen_audit_legacy", "kitchen_audit_entries", type_="unique")
    op.drop_column("kitchen_audit_entries", "legacy_id")
    op.drop_constraint("uq_inventory_batch_legacy", "inventory_batches", type_="unique")
    op.drop_column("inventory_batches", "legacy_id")
    op.drop_constraint("uq_guidance_rule_legacy", "guidance_rules", type_="unique")
    op.drop_column("guidance_rules", "legacy_id")
    op.drop_index(op.f("ix_recipe_allergens_recipe_id"), table_name="recipe_allergens")
    op.drop_table("recipe_allergens")
    op.drop_index(op.f("ix_household_allergies_household_id"), table_name="household_allergies")
    op.drop_table("household_allergies")
    op.drop_table("household_kitchen_settings")
    # ### end Alembic commands ###
