import {applyRecurring,toggleRecurring} from "./recurring";
import { prepSchedule, projectedMealShortages } from "./schedule";
import { MEAL_TAGS, repin } from "./tag-pins";
import type { AuditEntry, CommandResult, InventoryItem, KitchenCommand, KitchenState, KnowledgeDocument, Meal, PrepTask, WeeklyPlan, PlanningWorkflow } from "./types";

type Undo = {planId:string;collection:"meals"|"prep";entityId:string;before:Meal|PrepTask;after:Meal|PrepTask;inventoryAfter:KitchenState["inventory"];balances:Record<string,number>;created?:string[]};
type RecordEntry = AuditEntry & {undo?:Undo;undone?:boolean};
const clone = <T,>(value:T):T => JSON.parse(JSON.stringify(value)) as T;
function quantity(value:number) { if(!Number.isFinite(value)||value<0) throw new Error("Portions must be a non-negative number."); }
export function applyDemoCommand(original: KitchenState, command: KitchenCommand): CommandResult {
  if(original.audit.some(a=>a.operationId===command.operationId)) return {state:original,message:"Already saved."};
  if(command.expectedRevision!==original.revision) throw new Error("This workspace changed. Please refresh and try again.");
  const state=clone(original), p=command.payload;
  const stocked=new Set(original.inventory.map(i=>i.id));
  const findPlan=()=>{const x=state.plans.find(x=>x.id===p.planId);if(!x)throw new Error("Plan not found.");return x;};
  const findMeal=(plan:WeeklyPlan)=>{const x=plan.meals.find(x=>x.id===p.mealId);if(!x)throw new Error("Meal not found.");return x;};
  let message="Changes saved.", undo:Undo|undefined;let auditContext:Partial<AuditEntry>={}; const deltas:{inventoryId:string;amount:number}[]=[];
  /** Boxes this command brought into the fridge (an undo takes them away again). */
  const created=()=>[...new Set(deltas.map(d=>d.inventoryId).filter(id=>!stocked.has(id)))];
  const adjust=(deltas:{inventoryId:string;amount:number}[])=>{for(const d of deltas){const x=state.inventory.find(x=>x.id===d.inventoryId);if(!x)throw new Error("An inventory item is missing.");if(x.portions+d.amount<0)throw new Error(`Not enough ${x.name}. Update the portions or replace this ingredient.`);x.portions=Number((x.portions+d.amount).toFixed(4));}};
  const snapshot=(plan:WeeklyPlan,collection:"meals"|"prep",before:Meal|PrepTask,after:Meal|PrepTask):Undo=>({planId:plan.id,collection,entityId:before.id,before:clone(before),after:clone(after),inventoryAfter:clone(state.inventory.filter(i=>deltas.some(d=>d.inventoryId===i.id))),balances:Object.fromEntries(deltas.map(d=>[d.inventoryId,state.inventory.find(i=>i.id===d.inventoryId)!.portions])),...(created().length?{created:created()}:{})});
  const consume=(component:{inventoryId?:string;recipeId?:string;name?:string;portions:number})=>{quantity(component.portions);let remaining=component.portions;const candidates=state.inventory.filter(i=>component.inventoryId?i.id===component.inventoryId:component.recipeId?i.recipeId===component.recipeId:i.name.toLocaleLowerCase()===component.name?.toLocaleLowerCase()).sort((a,b)=>a.addedOn.localeCompare(b.addedOn)||a.id.localeCompare(b.id));for(const item of candidates){const amount=Math.min(remaining,item.portions);item.portions-=amount;remaining-=amount;if(amount)deltas.push({inventoryId:item.id,amount:-amount});}if(remaining>1e-8)throw new Error(`Not enough ${component.name||"stock"}: ${remaining} portions short.`);};
  const remember=(weekStart:string,workflow:PlanningWorkflow)=>{const entry=state.weeklyPrompts?.find(x=>x.weekStart===weekStart);state.weeklyPrompts=[...(state.weeklyPrompts||[]).filter(x=>x.weekStart!==weekStart),{weekStart,prompt:entry?.prompt??"",workflow}];};
  switch(command.type){
    case "knowledge.save": {
      const document=clone(p.document as KnowledgeDocument);
      if(!document.title?.trim()||!document.content?.trim()||!document.category?.trim()||document.title.length>200||document.content.length>100000||document.category.length>100)throw new Error("Check the document title, content and category.");
      if(document.sourceUrl){const url=new URL(document.sourceUrl);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("Source URL must use HTTP or HTTPS without credentials.");}
      const existing=(state.knowledgeDocuments||[]).find(item=>item.id===document.id);
      if(existing&&document.version!==undefined&&document.version!==existing.version)throw new Error("This document changed; reload it before saving edits.");
      document.title=document.title.trim();document.content=document.content.trim();document.category=document.category.trim();document.version=existing?existing.version+1:1;document.updatedAt=new Date().toISOString();
      state.knowledgeDocuments=[...(state.knowledgeDocuments||[]).filter(item=>item.id!==document.id),document];message="Knowledge document saved.";break;
    }
    case "knowledge.delete": {if(!(state.knowledgeDocuments||[]).some(item=>item.id===p.id))throw new Error("Document not found.");state.knowledgeDocuments=(state.knowledgeDocuments||[]).filter(item=>item.id!==p.id);message="Document deleted. Existing plan snapshots are preserved.";break;}

    case "recipe.save":{const recipe=clone(p.recipe as KitchenState["recipes"][number]);if(!recipe.name.trim())throw new Error("A recipe name is required.");quantity(recipe.servings);quantity(recipe.activeMinutes);quantity(recipe.elapsedMinutes);if(recipe.servings===0||recipe.elapsedMinutes<recipe.activeMinutes)throw new Error("Check servings and time estimates.");const i=state.recipes.findIndex(x=>x.id===recipe.id);if(i<0)state.recipes.push(recipe);else state.recipes[i]=recipe;state.tags=[...new Set([...state.tags,...recipe.tags])];message="Recipe saved.";break;}
    case "recipe.delete":{if(state.inventory.some(i=>i.recipeId===p.id)||state.plans.some(plan=>plan.meals.some(m=>m.components.some(c=>c.recipeId===p.id))||plan.prep.some(t=>t.recipeId===p.id)))throw new Error("This recipe is used in a plan. Replace it there first.");state.recipes=state.recipes.filter(x=>x.id!==p.id);message="Recipe removed.";break;}
    case "tag.save":{const name=String(p.name).trim();if(!name)throw new Error("Enter a tag name.");state.tags=[...new Set(state.tags.map(t=>t===p.previous?name:t).concat(name))];if(p.previous){state.recipes.forEach(r=>r.tags=[...new Set(r.tags.map(t=>t===p.previous?name:t))]);repin(state,pins=>pins.map(pin=>pin===p.previous?name:pin));}break;}
    case "tag.apply":{const name=String(p.name||"").trim();const ids=p.recipeIds as string[];if(!state.tags.includes(name)||!Array.isArray(ids)||!ids.length||ids.some(id=>!state.recipes.some(r=>r.id===id)))throw new Error("Choose an existing tag and recipes.");state.recipes.filter(r=>ids.includes(r.id)).forEach(r=>{r.tags=p.remove?r.tags.filter(t=>t!==name):[...new Set([...r.tags,name])];});message="Recipe tags updated.";break;}
    case "tag.delete":state.tags=state.tags.filter(t=>t!==p.name);state.recipes.forEach(r=>r.tags=r.tags.filter(t=>t!==p.name));repin(state,pins=>pins.filter(pin=>pin!==p.name));break;
    case "tag.pin":{const name=String(p.name).trim();if(!MEAL_TAGS.some(m=>m.slot===name)&&!state.tags.includes(name))throw new Error(`Unknown tag: ${name}`);repin(state,pins=>[...pins.filter(pin=>pin!==name),...(p.pinned?[name]:[])]);message=p.pinned?`${name} pinned`:`${name} unpinned`;break;}
    case "inventory.save":{const item=clone(p.item as KitchenState["inventory"][number]);quantity(item.portions);if(!item.name.trim())throw new Error("A food name is required.");const i=state.inventory.findIndex(x=>x.id===item.id);if(i<0)state.inventory.push(item);else state.inventory[i]=item;message="Fridge updated. Future meals have been checked.";break;}
    case "inventory.delete":{
      // As the server: a box a meal still to eat (or prep still to cook) needs
      // stays, with the reason; finished meals and prep, and past weeks, let go of it.
      const item=state.inventory.find(x=>x.id===p.id);if(!item)throw new Error("This food is no longer in the fridge.");
      const today=new Intl.DateTimeFormat("en-CA",{timeZone:state.settings.timezone}).format(new Date());
      for(const plan of state.plans){
        const over=new Date(`${plan.weekStart}T12:00:00Z`).getTime()+7*86_400_000<=new Date(`${today}T12:00:00Z`).getTime();
        const meal=plan.meals.find(m=>m.status==="planned"&&m.day>=today&&m.components.some(c=>c.inventoryId===item.id||plan.prep.some(t=>t.id===c.prepId&&t.status==="completed"&&t.outputInventoryId===item.id)));
        if(meal)throw new Error(`${item.name} is planned for ${new Date(`${meal.day}T12:00:00Z`).toLocaleDateString("en-US",{weekday:"short",timeZone:"UTC"})} ${meal.slot}. Replace it in that meal first.`);
        const task=over?undefined:plan.prep.find(t=>t.status==="planned"&&t.inputs.some(i=>i.inventoryId===item.id));
        if(task)throw new Error(`${item.name} is needed to cook ${task.name}. Change that prep first.`);
      }
      for(const plan of state.plans){
        plan.meals.forEach(m=>m.components.forEach(c=>{if(c.inventoryId===item.id)delete c.inventoryId;}));
        plan.prep.forEach(t=>{t.inputs=t.inputs.filter(i=>i.inventoryId!==item.id);if(t.outputInventoryId===item.id)delete t.outputInventoryId;});
      }
      state.inventory=state.inventory.filter(x=>x.id!==item.id);message="Removed from the fridge";break;}
    case "settings.save":{state.settings=clone(p.settings as KitchenState["settings"]);if(state.settings.people<1||state.settings.maxDailyActiveMinutes<1||state.settings.maxPrepMinutes<1||!Number.isInteger(state.settings.recipeRepeatGapDays??1)||(state.settings.recipeRepeatGapDays??1)<1||(state.settings.recipeRepeatGapDays??1)>7)throw new Error("Check the household and time settings.");try{new Intl.DateTimeFormat("en",{timeZone:state.settings.timezone});}catch{throw new Error("Enter a valid timezone.");}message="Planning preferences saved.";break;}
    case "planning.workflow": {const workflow=clone(p.workflow as PlanningWorkflow),week=String(p.weekStart),plan=workflow.planId?state.plans.find(x=>x.id===workflow.planId):null;if(workflow.planId&&!plan||plan&&plan.weekStart!==week||!plan&&workflow.step!=="preferences"||plan&&!(plan.status==="confirmed"?["confirmed","shopping"]:["preferences","adjust"]).includes(workflow.step))throw new Error("This step is not available for this plan.");remember(week,workflow);message="Planning progress saved.";break;}
    case "inventory.receive":{const items=Array.isArray(p.items)?p.items as InventoryItem[]:[];if(!items.length)throw new Error("Choose what you bought.");let added=0;for(const item of items){if(state.inventory.some(x=>x.id===item.id))continue;if(!item.name?.trim())throw new Error("Each item needs a name.");state.inventory.push(clone(item));added++;}message=`Added ${added} item${added===1?"":"s"} to the fridge.`;break;}
    case "inventory.arrange":{const order=Array.isArray(p.order)?p.order.map(String):[];const ids=state.inventory.map(i=>i.id);if(order.length!==ids.length||new Set(order).size!==order.length||order.some(id=>!ids.includes(id)))throw new Error("Arrange every item in the fridge exactly once.");for(const move of (Array.isArray(p.moves)?p.moves:[]) as {id:string;location:string}[]){const item=state.inventory.find(i=>i.id===move.id);if(!item||!String(move.location??"").trim())throw new Error("Choose an item and where it goes.");item.location=String(move.location).trim();}state.inventory=order.map(id=>state.inventory.find(i=>i.id===id)!);message="Fridge arranged.";break;}
    case "shopping.check": {const plan=findPlan();if(plan.status!=="confirmed")throw new Error("Confirm the plan before shopping.");const chosen=[...new Set(Array.isArray(p.keys)?p.keys.map(String):[String(p.key)])];if(!chosen.length||chosen.some(k=>!k.trim())||typeof p.checked!=="boolean")throw new Error("Choose a shopping item and a checked state.");plan.shoppingChecked=[...(plan.shoppingChecked||[]).filter(k=>!chosen.includes(k)),...(p.checked?chosen:[])];message="Shopping checklist saved.";break;}
    case "planning.prompt":{const weekStart=String(p.weekStart),prompt=String(p.prompt||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)||prompt.length>10000)throw new Error("Invalid week or weekly preferences.");const workflow=state.weeklyPrompts?.find(x=>x.weekStart===weekStart)?.workflow;state.weeklyPrompts=[...(state.weeklyPrompts||[]).filter(item=>item.weekStart!==weekStart),{weekStart,prompt,...(workflow?{workflow}:{})}];message="Weekly preferences saved.";break;}
    case "plan.save":{const plan=clone(p.plan as WeeklyPlan);const i=state.plans.findIndex(x=>x.id===plan.id);const old=state.plans[i];if(plan.status!=="draft"||old?.status==="confirmed")throw new Error("Create a separate draft, then confirm it.");const base=plan.basePlanId?state.plans.find(x=>x.id===plan.basePlanId):old;if(plan.basePlanId&&!base)throw new Error("Base plan not found.");if(plan.knowledgeSnapshot===undefined)plan.knowledgeSnapshot=clone(base?base.knowledgeSnapshot||[]:(state.knowledgeDocuments||[]).filter(d=>d.enabled));if(plan.guidanceSnapshot===undefined)plan.guidanceSnapshot=clone(base?base.guidanceSnapshot||[]:state.settings.guidance.filter(g=>g.enabled));if(base){for(const meal of base.meals){if((meal.locked||meal.status!=="planned")&&JSON.stringify(plan.meals.find(m=>m.id===meal.id))!==JSON.stringify(meal))throw new Error("Locked or executed meals must be preserved.");}for(const task of base.prep){if(task.status!=="planned"&&JSON.stringify(plan.prep.find(t=>t.id===task.id))!==JSON.stringify(task))throw new Error("Executed prep must be preserved.");}}if(plan.meals.some(m=>m.status!=="planned"&&!base?.meals.some(old=>JSON.stringify(old)===JSON.stringify(m)))||plan.prep.some(t=>t.status!=="planned"&&!base?.prep.some(old=>JSON.stringify(old)===JSON.stringify(t))))throw new Error("Execution must use status commands.");applyRecurring(state,plan);delete plan.fulfillment;plan.version=old?old.version+1:1;if(i<0){state.plans.push(plan);remember(plan.weekStart,{planId:plan.id,step:"adjust",focus:"shopping"});}else state.plans[i]=plan;message="Draft saved.";break;}
    case "plan.confirm":{const plan=state.plans.find(x=>x.id===p.id);if(!plan)throw new Error("Plan not found.");if(plan.status==="confirmed")throw new Error("Plan is already confirmed.");const existing=state.plans.find(x=>x.status==="confirmed"&&x.weekStart===plan.weekStart);if(existing&&(existing.id!==plan.basePlanId||existing.version!==plan.baseVersion))throw new Error("Confirmed plan changed. Reconcile the draft first.");if(plan.basePlanId){const base=state.plans.find(x=>x.id===plan.basePlanId);if(base&&base.version!==plan.baseVersion)throw new Error("The confirmed plan changed. Review the latest version first.");}prepSchedule(state,plan);if(projectedMealShortages(state,plan).length)throw new Error("Insufficient stock for this plan.");if(plan.basePlanId){const base=state.plans.find(x=>x.id===plan.basePlanId);if(base){base.status="draft";base.version++;}}plan.status="confirmed";plan.version++;remember(plan.weekStart,{planId:plan.id,step:"shopping",focus:"shopping"});message="Plan confirmed. Your calendar is ready.";break;}
    case "meal.save":{for(const recipe of (p.recipes as KitchenState["recipes"]|undefined)||[]){if(state.recipes.some(r=>r.id===recipe.id))throw new Error("Save existing recipe edits separately.");state.recipes.push(clone(recipe));state.tags=[...new Set([...state.tags,...recipe.tags])];}const plan=findPlan(),meal=clone(p.meal as Meal),old=plan.meals.find(m=>m.id===meal.id);if(old&&(old.status!=="planned"||old.locked))throw new Error("Unlock or undo execution before editing this meal.");if(meal.status!=="planned"||meal.locked)throw new Error("Use the status and lock commands.");if(plan.meals.some(m=>m.id!==meal.id&&m.day===meal.day&&m.slot===meal.slot))throw new Error("There is already a meal in that slot.");if(!meal.components.length)throw new Error("Add at least one component.");meal.components.forEach(c=>{quantity(c.portions);if(!c.portions||!c.name.trim())throw new Error("Food and positive portions required.");});quantity(meal.activeMinutes);quantity(meal.elapsedMinutes);if(meal.elapsedMinutes<meal.activeMinutes||!meal.elapsedMinutes)throw new Error("Check active and elapsed time.");if(old){undo=snapshot(plan,"meals",old,meal);plan.meals[plan.meals.indexOf(old)]=meal;}else plan.meals.push(meal);plan.version++;message="Meal updated across Calendar and Plan.";break;}
    case "meal.leftovers":{const plan=findPlan(),meal=findMeal(plan),component=meal.components.find(c=>c.id===p.componentId);if(plan.status!=="confirmed"||meal.status!=="completed"||!component)throw new Error("Record leftovers after completing this meal.");const amount=Number(p.portions);quantity(amount);const returned=state.audit.filter(a=>a.kind==="meal.leftovers"&&!a.undone&&a.planId===plan.id&&a.entityId===meal.id&&a.componentId===component.id).reduce((sum,a)=>sum+(a.deltas||[]).reduce((n,d)=>n+d.amount,0),0);if(amount<=0||amount+returned>component.portions)throw new Error("Leftovers exceed the prepared portions.");const id=crypto.randomUUID();state.inventory.push({id,name:component.name,type:component.type,recipeId:component.recipeId,portions:amount,location:String(p.location||"Fridge"),prepared:true,addedOn:new Date().toISOString().slice(0,10),priority:false});deltas.push({inventoryId:id,amount});undo=snapshot(plan,"meals",meal,meal);auditContext={planId:plan.id,entityId:meal.id,componentId:component.id};plan.version++;message="Leftovers added to fridge.";break;}
    case "meal.include":{if(typeof p.included!=="boolean")throw new Error("Invalid flag.");const plan=findPlan(),meal=findMeal(plan);if(meal.status!=="planned")throw new Error("Only a planned meal can be left out.");meal.included=p.included;plan.version++;message=p.included?"Slot planned again.":"Slot excluded.";break;}
    case "plan.presets":{if(!Array.isArray(p.keys))throw new Error("Invalid presets.");const plan=findPlan();plan.presets=[...new Set((p.keys as unknown[]).map(String))];plan.version++;message="Presets saved.";break;}
    case "meal.like":{if(typeof p.liked!=="boolean")throw new Error("Invalid flag.");const plan=findPlan();findMeal(plan).liked=p.liked;plan.version++;message=p.liked?"Saved: baby liked this meal.":"Like removed.";break;}
    case "meal.lock":{if(typeof p.locked!=="boolean")throw new Error("Invalid flag.");const plan=findPlan();toggleRecurring(state,plan,findMeal(plan),p.locked);plan.version++;message=p.locked?"Meal locked for future planning.":"Meal unlocked.";break;}
    case "meal.status":{const plan=findPlan(),meal=findMeal(plan);if(plan.status!=="confirmed")throw new Error("Confirm this plan before recording a meal.");if(!["planned","completed","skipped"].includes(String(p.status)))throw new Error("Invalid execution status.");if(meal.status===p.status)break;if(meal.status!=="planned"||p.status==="planned")throw new Error("Undo the previous execution first.");const before=clone(meal);if(p.status==="completed")for(const component of meal.components){if(!component.inventoryId&&!component.prepId)continue;const selected={...component};if(component.prepId){const prep=plan.prep.find(t=>t.id===component.prepId);if(!prep||prep.status!=="completed")throw new Error("Prep is not complete.");if(!prep.outputInventoryId)throw new Error(`${prep.name} is no longer in the fridge.`);selected.inventoryId=prep.outputInventoryId;}consume(selected);}meal.status=p.status as Meal["status"];undo=snapshot(plan,"meals",before,meal);plan.version++;message=meal.status==="completed"?"Meal completed. Fridge portions updated.":"Meal skipped. Your food stays in the fridge.";break;}
    case "prep.delete":{const plan=findPlan(),task=plan.prep.find(item=>item.id===p.prepId);if(!task||task.status!=="planned")throw new Error("Undo execution before removing prep.");if(plan.meals.some(m=>m.components.some(c=>c.prepId===task.id))||plan.prep.some(t=>t.dependencies.includes(task.id)))throw new Error("This task is used by meals or prep. Replace those references first.");plan.prep=plan.prep.filter(t=>t.id!==task.id);plan.version++;message="Prep task removed.";break;}
    case "prep.save":{const plan=findPlan(),task=clone(p.prep as PrepTask),existing=plan.prep.find(item=>item.id===task.id);if(existing&&existing.status!=="planned")throw new Error("Undo execution before editing prep.");if(task.status!=="planned"||task.actualPortions!==0||!task.name.trim()||task.plannedPortions<0||(task.recipeId&&task.plannedPortions<=0)||task.elapsedMinutes<=0||task.elapsedMinutes<task.activeMinutes)throw new Error("Check the prep task and its timing.");if(existing)plan.prep[plan.prep.indexOf(existing)]=task;else plan.prep.push(task);prepSchedule(state,plan);plan.version++;message="Prep task saved.";break;}
    case "prep.like":{const task=findPlan().prep.find(t=>t.id===p.prepId);if(!task)throw new Error("Prep task not found.");if(typeof p.liked!=="boolean")throw new Error("Invalid flag.");task.liked=p.liked;break;}
    case "prep.status":{const plan=findPlan(),task=plan.prep.find(t=>t.id===p.prepId);if(!task)throw new Error("Prep task not found.");if(plan.status!=="confirmed")throw new Error("Confirm the plan before starting prep.");if(!["planned","completed","skipped"].includes(String(p.status)))throw new Error("Invalid execution status.");if(task.status===p.status)break;if(task.status!=="planned"||p.status==="planned")throw new Error("Undo the previous execution first.");const before=clone(task);if(p.status==="completed"){if(task.dependencies.some(id=>plan.prep.find(t=>t.id===id)?.status!=="completed"))throw new Error("Complete prerequisite prep first.");const actual=p.actualPortions??task.plannedPortions;if(typeof actual!=="number")throw new Error("Actual portions must be numeric.");quantity(actual);task.inputs.forEach(consume);const quick=!task.recipeId&&!task.outputInventoryId&&actual===0;if(!quick){const id=task.outputInventoryId||`prep-${task.id}`;let item=state.inventory.find(x=>x.id===id);if(!item){item={id,name:task.name,type:task.type==="Baking"?"Carbs":task.type,portions:0,location:"Freezer",prepared:true,addedOn:new Date().toISOString().slice(0,10),priority:false,recipeId:task.recipeId};state.inventory.push(item);}else if(item.name!==task.name||item.recipeId!==task.recipeId)throw new Error("Prep output does not match the selected inventory batch.");else if(item.portions===0)item.location="Freezer";task.outputInventoryId=id;item.portions+=actual;deltas.push({inventoryId:id,amount:actual});}task.actualPortions=actual;}task.status=p.status as PrepTask["status"];undo=snapshot(plan,"prep",before,task);plan.version++;message=task.status==="completed"?`Added ${task.actualPortions} portions to your fridge.`:"Prep skipped. Check the affected meals.";break;}
    case "change.undo":{const record=state.audit.find(a=>a.id===p.auditId) as RecordEntry|undefined;const u=record?.undo;if(!record||!u||record.undone)throw new Error("This change can no longer be undone.");const plan=state.plans.find(x=>x.id===u.planId);if(!plan)throw new Error("The plan changed. Please review it first.");if(["meal.status","prep.status"].includes(record.kind)&&plan.status!=="confirmed")throw new Error("This plan was superseded; undo is unsafe.");const entity=plan[u.collection].find(item=>item.id===u.entityId);if(!entity)throw new Error("Record no longer exists.");const structural=(value:Meal|PrepTask)=>JSON.stringify({...value,liked:false});if(structural(entity)!==structural(u.after))throw new Error("This record changed after that action; undo is unsafe.");const touched=new Set(Object.keys(u.balances));if(state.audit.slice(state.audit.indexOf(record)+1).some(a=>!a.undone&&a.kind==="meal.leftovers"&&a.planId===u.planId&&a.entityId===u.entityId))throw new Error("Undo recorded leftovers before undoing this meal.");if(state.audit.slice(state.audit.indexOf(record)+1).some(a=>!(a as RecordEntry).undone&&a.deltas?.some(d=>touched.has(d.inventoryId))))throw new Error("Dependent stock activity prevents undo.");for(const item of u.inventoryAfter){if(JSON.stringify(state.inventory.find(i=>i.id===item.id))!==JSON.stringify(item))throw new Error("Stock changed after that action; undo is unsafe.");}const reversed=(record.deltas||[]).map(d=>({...d,amount:-d.amount}));adjust(reversed);const liked=entity.liked;Object.keys(entity).forEach(key=>delete (entity as unknown as Record<string,unknown>)[key]);Object.assign(entity,clone(u.before),{liked});
      // A box that action brought into the fridge leaves with it, unless something now points at it.
      const used=new Set(state.plans.flatMap(pl=>[...pl.meals.flatMap(m=>m.components.map(c=>c.inventoryId)),...pl.prep.flatMap(t=>t.inputs.map(i=>i.inventoryId)),...pl.prep.filter(t=>t.status==="completed").map(t=>t.outputInventoryId)]));
      const emptied=new Set((u.created??[]).filter(id=>state.inventory.find(i=>i.id===id)?.portions===0&&!used.has(id)));
      state.inventory=state.inventory.filter(i=>!emptied.has(i.id));deltas.push(...reversed.filter(d=>!emptied.has(d.inventoryId)));record.undone=true;plan.version++;message="Change undone. Related portions restored.";break;}
    case "plan.chat":{const plan=findPlan();if(!Array.isArray(p.messages)||!p.messages.length)throw new Error("Provide chat messages.");for(const entry of p.messages as WeeklyPlan["chat"]){if(!entry.id||!["user","assistant"].includes(entry.role)||!entry.text?.trim()||entry.mealIds?.some(id=>!plan.meals.some(m=>m.id===id)))throw new Error("Invalid chat message or meal reference.");if(!plan.chat.some(m=>m.id===entry.id))plan.chat.push(clone(entry));}break;}
    default:throw new Error("This action is not available in the demo.");
  }
  const record:RecordEntry={id:crypto.randomUUID(),kind:command.type,message,at:new Date().toISOString(),operationId:command.operationId,undo,deltas,undone:false,...auditContext};
  state.audit.push(record);state.revision++;
  return {state,message};
}
