"use client";
import { useState } from "react";
import { ANALYSIS_METRICS } from "./analysis";
import type { Guidance, KitchenSettings, PageProps } from "./types";
export function GuidancePage({ state, send, demo, navigate }: PageProps) {
  const [settings, setSettings] = useState<KitchenSettings>(structuredClone(state.settings));
  const [editing, setEditing] = useState<Guidance | null>(null);
  const [error, setError] = useState("");
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [busy, setBusy] = useState(false);
  const [remove, setRemove] = useState<string | null>(null);
  const updateGuidance = async (guidance: Guidance[]) => send("settings.save", { settings: { ...state.settings, guidance } });
  const change = (patch: Partial<KitchenSettings>) => setSettings(s => ({ ...s, ...patch }));
  return <section className="kw-support-page kw-settings-page"><header className="kw-page-header"><h1>⚙️ Settings</h1></header><div className="kw-settings-layout"><aside className="kw-settings-nav"><a href="#household-settings" onClick={()=>setSettingsOpen(true)}>General Settings ⚙️</a><a className="active" href="#dietary-guidelines">Planning Guidance 📋</a><a href="#family-profile">Family Profile 👪</a><button onClick={()=>navigate("knowledge")}>Nutrition Knowledge 📚</button></aside><div className="kw-settings-content"><div className="kw-guidance-columns"><section className="kw-guidelines" id="dietary-guidelines"><h2>Dietary Guidelines 📋</h2>
    {editing && <form className="kw-card kw-support-editor" onSubmit={async e => { e.preventDefault(); setBusy(true); const existing = state.settings.guidance.find(g => g.id === editing.id); const next = { ...editing, title: editing.title.trim(), content: editing.content.trim(), version: existing ? existing.version + 1 : 1 }; try { if (await updateGuidance([...state.settings.guidance.filter(g => g.id !== editing.id), next])) setEditing(null); } finally { setBusy(false); } }}><h2>{state.settings.guidance.some(g => g.id === editing.id) ? "Edit guidance" : "New guidance"}</h2><label className="kw-label">Title<input autoFocus className="kw-input" required value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label className="kw-label">Instructions<textarea className="kw-input" required rows={4} value={editing.content} onChange={e => setEditing({ ...editing, content: e.target.value })} /></label><div className="kw-support-actions"><button className="kw-button kw-primary" disabled={busy || !editing.title.trim() || !editing.content.trim()}>Save guidance</button><button className="kw-button" type="button" onClick={() => setEditing(null)}>Cancel</button></div></form>}
    <div className="kw-support-grid kw-guidance-list">{state.settings.guidance.map(g => <article className="kw-card kw-support-task" key={g.id}><div className="kw-row"><details className="kw-guidance-content"><summary><h3>{g.title}</h3></summary><p className="kw-support-prewrap">{g.content}</p><small>Version {g.version}</small></details><label className="kw-support-toggle"><span className="sr-only">Enable {g.title}</span><input type="checkbox" checked={g.enabled} onChange={e => updateGuidance(state.settings.guidance.map(item => item.id === g.id ? { ...item, enabled: e.target.checked, version: item.version + 1 } : item))} /></label></div><div className="kw-support-actions"><button className="kw-button" onClick={() => setEditing({ ...g })} aria-label={`Edit ${g.title}`}>✏️</button>{remove === g.id ? <><button className="kw-button" onClick={async () => { if (await updateGuidance(state.settings.guidance.filter(item => item.id !== g.id))) setRemove(null); }}>Confirm delete</button><button className="kw-button" onClick={() => setRemove(null)}>Cancel</button></> : <button className="kw-button" onClick={() => setRemove(g.id)} aria-label={`Delete ${g.title}`}>🗑️</button>}</div></article>)}</div>
    {!state.settings.guidance.length && <p className="kw-empty">Add preferences such as familiar breakfasts or fewer repeated dinners.</p>}
<button className="kw-add-guideline" onClick={() => setEditing({ id: crypto.randomUUID(), title: "", content: "", enabled: true, version: 1 })}>+ Add guideline</button></section>
    <section className="kw-guidelines kw-metric-settings" id="analysis-metrics" aria-label="Analysis metrics"><h2>Analysis Metrics 📊</h2>
      {ANALYSIS_METRICS.map(metric => { const chosen = state.settings.analysisMetrics ?? ANALYSIS_METRICS.map(m => m.id); const on = chosen.includes(metric.id);
        return <label className="kw-metric-setting" key={metric.id}><input type="checkbox" checked={on} aria-label={`Analyze ${metric.label}`} onChange={e => void send("settings.save", { settings: { ...state.settings, analysisMetrics: ANALYSIS_METRICS.map(m => m.id).filter(id => id === metric.id ? e.target.checked : chosen.includes(id)) } })} /><span><strong>{metric.label}</strong><small>{metric.rule}</small></span></label>; })}
    </section></div>
    <div className="kw-settings-summaries"><section className="kw-card" id="family-profile"><h2>Family Conditions 👪</h2><p>🏠 Family Size: {state.settings.people} portions · Child: {state.settings.childAge} months</p><p>⚠ Allergies: {state.settings.allergies.join(", ")||"None recorded ✅"}</p><p className="kw-muted">Available Kitchen Equipment:</p><div className="kw-support-tags">{[...new Set(state.recipes.flatMap(r=>r.equipment??[]))].map(item=><span className="kw-pill" key={item}>{item}</span>)}</div></section><section className="kw-card"><h2>Planning Preferences 🎯</h2><dl><div><dt>Weekly new dishes:</dt><dd className="kw-preference-stepper"><button className="kw-icon bordered" aria-label="Fewer new recipes" disabled={state.settings.newRecipesPerWeek<=0||busy} onClick={async()=>{setBusy(true);try{const value=state.settings.newRecipesPerWeek-1;if(await send("settings.save",{settings:{...state.settings,newRecipesPerWeek:value}}))change({newRecipesPerWeek:value});}finally{setBusy(false);}}}>←</button><strong>{state.settings.newRecipesPerWeek}</strong><button className="kw-icon bordered" aria-label="More new recipes" disabled={busy||state.settings.newRecipesPerWeek>=21} onClick={async()=>{setBusy(true);try{const value=state.settings.newRecipesPerWeek+1;if(await send("settings.save",{settings:{...state.settings,newRecipesPerWeek:value}}))change({newRecipesPerWeek:value});}finally{setBusy(false);}}}>→</button></dd></div><div><dt>Time budget / day:</dt><dd>{state.settings.maxDailyActiveMinutes} min ⏱</dd></div><div><dt>Weekend prep limit:</dt><dd>{state.settings.maxPrepMinutes/60} hours 🥣</dd></div><div><dt>Auto-generate:</dt><dd>Friday @ {state.settings.generateTime} 📅</dd></div></dl></section></div>
    <details className="kw-settings-edit" id="household-settings" open={settingsOpen} onToggle={e=>setSettingsOpen(e.currentTarget.open)}><summary>Edit household & schedule</summary>
    <form className="kw-card kw-support-editor" onSubmit={async e => { e.preventDefault(); setError(""); try { new Intl.DateTimeFormat("en", { timeZone: settings.timezone }); } catch { setError("Enter a valid IANA timezone, such as America/Los_Angeles."); return; } setBusy(true); try { await send("settings.save", { settings: { ...settings, allergies: settings.allergies.map(value => value.trim()).filter(Boolean), guidance: state.settings.guidance } }); } finally { setBusy(false); } }}><h2>Household & schedule</h2><p className="kw-muted">{demo ? "Demo settings are saved locally. Scheduled generation does not run in demo mode." : "A new draft is scheduled for Friday at your local generation time. Plans stay unconfirmed until you review them."}</p><div className="kw-form-grid">
      {([ ["people", "Household portions", 1], ["childAge", "Child age (months)", 0], ["maxPrepMinutes", "Prep elapsed limit (min)", 1], ["maxDailyActiveMinutes", "Daily active limit (min)", 1], ["newRecipesPerWeek", "New recipes per week", 0] ] as const).map(([key, label, min]) => <label className="kw-label" key={key}>{label}<input className="kw-input" required type="number" min={min} step="1" value={settings[key]} onChange={e => change({ [key]: e.target.valueAsNumber })} /></label>)}
      <label className="kw-label">Days between repeated dishes<input className="kw-input" type="number" min="1" max="7" step="1" required value={settings.recipeRepeatGapDays??1} onChange={e=>change({recipeRepeatGapDays:e.target.valueAsNumber})}/><span className="kw-muted">One clear day by default: Monday’s dish can return Wednesday.</span></label>
      <label className="kw-label">Allergies (comma separated)<input className="kw-input" value={settings.allergies.join(", ")} onChange={e => change({ allergies: e.target.value.split(",").map(s => s.trim()) })} /></label>
      <label className="kw-label">Timezone<input className="kw-input" required value={settings.timezone} onChange={e => change({ timezone: e.target.value })} /></label>
      <label className="kw-label">Friday generation time<input className="kw-input" type="time" required value={settings.generateTime} onChange={e => change({ generateTime: e.target.value })} /></label>
      <label className="kw-label">Prep day<select className="kw-input" value={settings.prepDay} onChange={e => change({ prepDay: Number(e.target.value) })}>{["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"].map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label>
    </div>{error && <p role="alert" className="kw-error">{error}</p>}<button className="kw-button kw-primary" disabled={busy}>Save settings</button></form>
    </details></div></div>
  </section>;
}
